services:
  - type: web
    name: my-flask-app
    runtime: python
    buildCommand: ""
    startCommand: "python flask_app.py"
services:
  - type: web
    name: my-flask-app
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python flask_app.py"
    envVars:
      - key: FLASK_ENV
        value: production